### ISSUE TITLE
Make graph rendering optional

### ISSUE THREAD

**Issue by hermanschaaf** [netlify/delta-action#330]
First off, thanks for this project, it's a great idea and so easy to use!

The graph rendering feature is very neat, but when you have a number of benchmarks it can take up several pages. I was hoping to have something more compact, so was surprised to see graphs the first time, because it doesn't match the screenshot in the README: 

![](https://user-images.githubusercontent.com/4162329/115129623-8acac500-9fdf-11eb-9bfc-822a415cb436.png)

Could graph rendering be made into an optional feature, with the other option being the simpler increase/decrease text?

**Comment by eduardoboucas** [comment]
I think that makes a lot of sense. Would you be open to submitting a PR?

**Comment by hermanschaaf** [comment]
@eduardoboucas My node.js is not great, but I can give it a shot 😅
